server:
  port: 8080
  #servlet:
  #context-path: /api/v1
  error:
    include-message: always
#MP_RGP_DENUNCIA_BDD
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Pegasus2021.
    url: jdbc:sqlserver://172.18.31.22:1433;databaseName=service_denuncia_qa2;encrypt=true;trustServerCertificate=true;
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso-rhsso-rgp-dev.apps.preprod.minpublico.cl/auth/realms/rgp
          jwk-set-uri: https://sso-rhsso-rgp-dev.apps.preprod.minpublico.cl/auth/realms/rgp/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

